crud/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('todos/', include("todos.urls")),
]

todos/urls.py
from django.urls import path

from . import views

app_name = "todos"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="details"),
    path("create/", views.create, name="create"),
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    class Status(models.TextChoices):
        IN_PROGRESS = 'IN_PROGRESS'
        COMPLETED = 'COMPLETED'
    
    title = models.CharField(max_length=200, null=False)
    body = models.TextField(null=False)
    status = models.CharField(choices=Status.choices, default=Status.IN_PROGRESS, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

crud/views.py
from django.shortcuts import render
from django.http import HttpRequest

def index(request: HttpRequest):
    return render(request, "index.html")

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest, Http404
from todos.models import Todo
from django.views import generic

from django.db.models import F
from django.urls import reverse

# Create your views here.


class IndexView(generic.ListView):
    model = Todo
    template_name = "todos/index.html"


class DetailView(generic.DetailView):
    model = Todo
    template_name = "todos/details.html"


# def index(request: HttpRequest):
#     todos = Todo.objects.order_by("-created_at")

#     return render(request, "todos/index.html", {"todos": todos})


# def details(request: HttpRequest, id: int):
#     todo = get_object_or_404(Todo, pk=id)

#     return render(request, "todos/details.html", {"todo": todo})


def create(request: HttpRequest):
    try:
        title_input = request.POST["title"]
        body_input = request.POST["body"]

        if title_input.strip() == "":
            raise KeyError()

        todo = Todo()
        todo.title = title_input
        todo.body = body_input
        todo.save()

        return redirect("todos:index")

    except KeyError:
        return render(request, "todos/index.html", {"error_message": "Invalid todo"})

templates/index.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body>
		<div class="container mx-auto">
			<section class="flex flex-col items-center justify-center h-screen gap-5">
				<h1 class="text-5xl font-bold">Welcome to Django Todo</h1>
				<a href="{% url 'todos:index' %}" class="hover:underline hover:text-emerald-500">Todo List</a>
			</section>
		</div>
	</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

todos/templates/todos/details.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Details</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
</head>
<body>
    <h1>Todo Details</h1>
    <p>Title: {{ todo.title }}</p>
    <p>Body: {{ todo.body }}</p>
</body>
</html>

todos/templates/todos/index.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Todo List</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="//unpkg.com/alpinejs" defer></script>
    {% tailwind_css %}
  </head>

  <body>
    <form action="{% url 'todos:create' %}" method="post" class="px-5 mt-5">
      <h2 class="text-3xl font-bold text-blue-700">Add a Todo</h2>

      {% csrf_token %}
      <fieldset class="flex flex-col-reverse">
        <input type="text" name="title" id="title-input" class="max-w-xs px-2 py-1" />
        <label for="title-input">Title</label>
      </fieldset>
      <fieldset class="flex flex-col-reverse">
        <textarea name="body" id="body-input" class="max-w-xs px-2 py-1 resize-y"></textarea>
        <label for="body-input">Body</label>
      </fieldset>
      <input type="submit" value="Add" class="p-2 text-white bg-blue-700 cursor-pointer" />
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}
    </form>

    <hr class="w-full my-5 border border-blue-300" />

    <section class="px-5">
      <h2 class="text-3xl font-bold text-blue-700">Todo List</h2>
      {% if todo_list %}
      <ul class="list-disc list-inside">
        {% for todo in todo_list %}
        <li>
          <a href="{% url 'todos:details' todo.id %}" class="underline">{{ todo.title }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>No todos are available.</p>
      {% endif %}
    </section>

    <div x-data='{ toggle: true, model: "" }'>
      <p x-show="toggle" x-text="model"></p>
      <input type="text" x-model="model" />
      <button x-on:click="toggle = !toggle">Toggle Togollll</button>
    </div>
  </body>
</html>